buzzwave/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt',  TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buzzwave/website/urls.py
from django.urls.conf import path
from django.contrib.auth.views import LogoutView

from website.views.authentication_views.auth_views import HomeView, LoginView, SignupView, FindUsernameView, ActivationConfirmView, activate, contact, subscribe
from website.views.authentication_views.password_reset_views import UserPasswordResetView, UserPasswordResetDoneView, CustomPasswordResetConfirmView, UserPasswordResetCompleteView
from website.views.authentication_views.validate_views import check_username, check_email, check_birth
from website.views.blog_views.blog_views import BlogView, BlogCreateView, BlogDetailView, BlogEditView
from website.views.blog_views.summernote_views import summernote_image_upload_view

app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='website:home'), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('activation-confirm/', ActivationConfirmView.as_view(), name='activation_confirm'),
    path('activate/<str:uidb64>/<str:token>/', activate, name="activate"),

    path('find/username/', FindUsernameView.as_view(), name='find_username'),
    path('password-reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset-done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),


    path('contact/', contact),
    path('subscribe/', subscribe),

    path('check-username/', check_username),
    path('check-email/', check_email),
    path('check-birth/', check_birth),

    path('blog/', BlogView.as_view(), name='blog'),
    path('blog-create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog-edit/<int:pk>/', BlogEditView.as_view(), name='blog_edit'),
    path('summernote/upload-image/', summernote_image_upload_view),
]

buzzwave/website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    membername = models.CharField(default='', max_length=100, verbose_name='회원명')
    phone = models.CharField(default='', max_length=30, verbose_name='전화번호')
    birth = models.DateField(null=True, verbose_name='생년월일')
    company = models.CharField(default='', max_length=50, verbose_name='회사')
    withdrawal_at = models.DateTimeField(null=True, verbose_name='탈퇴일')
    email_verified = models.BooleanField(default=False, verbose_name='이메일 인증여부')

    class Meta:
        db_table='auth_profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Subscriber(models.Model):
    email = models.EmailField(verbose_name='이메일', unique=True)
    is_activate = models.BooleanField(default=True, verbose_name='활성화여부')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='최초구독일')

    class Meta:
        db_table='subscriber'

class Blog(models.Model):
    image = models.ImageField(null=True, upload_to="image/blog/", verbose_name="썸네일")
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "blog"

class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='태그명', unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "tag"


class BlogTag(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_tag')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='blog_tag')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "blog_tag"

buzzwave/templates/includes/website/footer.html
{% load static %}

<footer class="footer">
  <div class="footer_container container">
      <div class="footer_inner">
          <ul>
              <li>상호명: D'Nova | 대표: 이현준</li>
              <li>
                  연락처: 010 8967 1353 | 이메일:
                  <a href="mailto:dnova@d-nova.com"
                      >dnova@d-nova.com</a
                  >
              </li>
              <li>
                  주소: 서울 | 사업자등록번호: 123-45-67890 |
                  통신판매: 1234-서울-1234 | 호스팅제공자: D'Nova
              </li>
              <li></li>
          </ul>
          <p>© 2024 D'Nova, All Rights Reserved</p>
      </div>
  </div>
</footer>

buzzwave/templates/includes/website/navbar.html
{% load static %}

<header class="header">
  <div class="header_container container">
      <a href="{% url 'website:home' %}" class="header_logo">
          <img src="{% static 'images/icons/icon_logo.png' %}" alt="D'Nova" />
      </a>
      <div class="header_inner">
          <nav class="header_nav">
              <ul>
                  <li>
                      <a href="{% if request.path != '/' %}/{% endif %}#about">회사소개</a>
                  </li>
                  <li>
                      <a href="{% if request.path != '/' %}/{% endif %}#price">이용금액</a>
                  </li>
                  <li>
                      <a href="{% url 'website:blog' %}">블로그</a>
                  </li>
                  <li>
                      <a href="{% if request.path != '/' %}/{% endif %}#contact">문의하기</a>
                  </li>
              </ul>
          </nav>
          {% if user.is_authenticated %}
            <a href="{% url 'website:logout' %}">로그아웃</a>
          {% else %}
            <a href="{% url 'website:login' %}">로그인</a>
          {% endif %}
      </div>
  </div>
</header>

buzzwave/templates/layouts/website_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %}
    {% endblock %}

    {% block title %}
    <title>D'Nova | Follow up SNS Trend</title>
    {% endblock %}

    <link rel="stylesheet" href="{% static 'css/swiper.bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/common.css' %}?v=20241220" />
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    {% block stylesheets %}{% endblock stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-D2S6KD6CFZ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-D2S6KD6CFZ');
    </script>
  </head>

  {% csrf_token %}
  {% block body %}
  <body>
    <div class="__web">
      {% block navbar %}
          {% include 'includes/website/navbar.html' %}
      {% endblock %}
      {% block main %}
      <main class="main">
        {% block content %}

        {% endblock %}

      </main>
        {% block footer %}
          {% include 'includes/website/footer.html' %}
        {% endblock %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{% static 'js/swiper.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block javascripts %}
    {% endblock javascripts %}
  </body>
  {% endblock %}
</html>

buzzwave/website/templates/authentication/activation_complete.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 이메일 인증완료</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}

{% block content %}

<section class="login_section">
    <div class="login_container container">
        <form id="loginForm">
            <h2>이메일 인증완료</h2>

            <div class="not_">                
                <span>이메일 주소가 성공적으로 확인되었습니다.</span>
                <a href="{% url 'website:login' %}">
                    로그인 하러가기? <span>로그인</span>
                </a>
            </div>
            <div class="find">
            </div>
            <button type="button" onclick="location.href=`{% url 'website:home' %}`">Home</button>
        </form>
    </div>
  </section>

{% endblock %}

{% block javascripts %}
{% endblock javascripts %}

buzzwave/website/templates/authentication/find_username.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 비밀번호 찾기</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}


{% block content %}
<section class="login_section">
  <div class="login_container container">
      <form id="emailform"  method='post' onsubmit="return false;">
          <h2>아이디 찾기</h2>
          <div class="i-box_container">
            <div class="i-box">
                <label for="email">이메일</label>
                <input
                    type="email"
                    id="email"
                    name="email"
                    placeholder="가입하신 이메일을 입력해주세요."
                    onkeyup="enterkey(this)"
                />
            </div>
            <p class="error" id="username-message"></p>
          </div>
          <div class="find">
            <a href="{% url 'website:password_reset' %}">비밀번호 찾기</a>
            </div>

          <button type="button" id="btn-submit">찾기</button>
      </form>
      <div class="not_">
          <a href="{% url 'website:login' %}">
            로그인 하러가기?  <span>로그인</span>
          </a>
      </div>
  </div>
</section>

{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'website/js/script_find_username.js' %}?v=20241220"></script>
{% endblock javascripts %}

buzzwave/website/templates/authentication/password_reset.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 비밀번호 찾기</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}


{% block content %}
<section class="login_section">
  <div class="login_container container">
      <form id="resetform"  method='post' action="{% url 'website:password_reset' %}" onsubmit="return false;">
        {% csrf_token %}
          <h2>비밀번호 재설정</h2>
          <div class="i-box_container">
            <div class="i-box">
                <label for="username">아이디</label>
                <input
                    type="text"
                    id="username"
                    name="username"
                    placeholder="아이디를 입력해주세요."
                    value="{{ form.username.value|default_if_none:'' }}"
                />
            </div>
              <div class="i-box">
                  <label for="email">이메일</label>
                  <input
                      type="text"
                      id="email"
                      name="email"
                      placeholder="가입하신 이메일을 입력해주세요."
                      value="{{ form.email.value|default_if_none:'' }}"
                  />
              </div>
              {% include "form_errors.html" %}
          </div>
          <div class="find" style="justify-content:flex-start">
            <span>사용자 가입 이메일 주소를 입력하시면 비밀번호 재설정 링크를 전송해 드립니다.</span>
          </div>
          <div class="find">
            <a href="{% url 'website:find_username' %}">아이디 찾기</a>
          </div>
          <button type="button" id="btn-submit">전송</button>
      </form>
      <div class="not_">
          <a href="{% url 'website:login' %}">
            로그인 하러가기?  <span>로그인</span>
          </a>
      </div>
  </div>
</section>

{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'website/js/script_user_password_reset.js' %}?v=20241220"></script>
{% endblock javascripts %}

buzzwave/website/templates/authentication/password_reset_complete.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 비밀번호 재설정</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}

{% block content %}

<section class="login_section">
  <div class="login_container container">
      <form id="loginForm">
          <h2>비밀번호 재설정 완료</h2>

          <div class="not_">                
              <span>새 비밀번호로 로그인해주세요.</span>
              <a href="{% url 'website:login' %}">
                  로그인 하러가기? <span>로그인</span>
              </a>
          </div>
          <div class="find">
          </div>
          <button type="button" onclick="location.href=`{% url 'website:home' %}`">Home</button>
      </form>
  </div>
</section>

{% endblock %}

{% block javascripts %}
{% endblock javascripts %}

buzzwave/website/templates/authentication/password_reset_confirm.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 비밀번호 재설정</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}

{% block content %}
<section class="login_section">
  <div class="login_container container">
    {% if validlink %}
      <form id="passwordForm"  method='post' onsubmit="return false;">
        {% csrf_token %}
          <h2>비밀번호 재설정</h2>
          <div class="i-box_container">
            <div class="i-box">
              <label for="new-password1">새 비밀번호</label>
              <input
                type="password"
                id="new-password1"
                name="new_password1"
                placeholder="새 비밀번호를 입력해주세요."
                value="{{ form.new_password1.value|default_if_none:'' }}"
                autocomplete="new-password"
              />
            </div>
            <div class="i-box">
              <label for="new-password2">새 비밀번호 확인</label>
              <input
                type="password"
                id="new-password2"
                name="new_password2"
                placeholder="새 비밀번호를 다시 입력해주세요."
                value="{{ form.new_password2.value|default_if_none:'' }}"
                autocomplete="new-password"
              />
            </div>
              <p class="error" id="password-error"></p>
          </div>
          <div class="find" style="justify-content:flex-start">
            <span>변경 하실 비밀번호를 입력해주세요.</span>
          </div>
          <button type="button" id="btn-submit">재설정</button>
      </form>
      <div class="not_">
          <a href="{% url 'website:login' %}">
            로그인 하러가기?  <span>로그인</span>
          </a>
      </div>
    {% else %}
    <form>
      <h2>유효하지 않은 링크입니다.</h2>
    </form>
    {% endif %}
  </div>
</section>
{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'website/js/script_user_password_reset_confirm.js' %}?v=20250103"></script>
{% endblock javascripts %}

buzzwave/website/templates/authentication/password_reset_done.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 비밀번호 재설정</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}

{% block content %}

<section class="login_section">
    <div class="login_container container">
        <form id="loginForm">
            <h2>비밀번호 재설정</h2>

            <div class="not_">                
                <span>비밀번호를 재설정할 수 있는 링크를 이메일로 전송했습니다. 몇 분 내로 이메일이 도착하지 않으면 스팸함을 확인해 보세요.</span>
                <a href="{% url 'website:login' %}">
                    로그인 하러가기? <span>로그인</span>
                </a>
            </div>
            <div class="find">
            </div>
            <button type="button" onclick="location.href=`{% url 'website:home' %}`">Home</button>
        </form>
    </div>
  </section>

{% endblock %}

{% block javascripts %}
{% endblock javascripts %}

buzzwave/website/templates/authentication/password_reset_done_fail.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 비밀번호 재설정</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}

{% block content %}

<section class="login_section">
    <div class="login_container container">
        <form id="loginForm">
            <h2>가입되지 않은 이메일 입니다.</h2>

            <div class="not_">                
                <span>가입 시 사용한 이메일을 입력해주세요.</span>
            </div>
            <div class="find">
            </div>
            <button type="button" onclick="location.href=`{% url 'website:password_reset' %}`">재시도</button>
        </form>
    </div>
  </section>

{% endblock %}

{% block javascripts %}
{% endblock javascripts %}

buzzwave/website/templates/authentication/user_login.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 로그인</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock stylesheets %}


{% block content %}

<section class="login_section">
  <div class="login_container container">
      <form id="loginForm">
          <h2>로그인</h2>
          <div class="i-box_container">
              <div class="i-box">
                  <label for="username">아이디</label>
                  <input
                      type="text"
                      id="username"
                      name="username"
                      placeholder="아이디를 입력해주세요."
                      onkeyup="enterkey(this)"
                  />
              </div>
              <div class="i-box">
                  <label for="password">비밀번호</label>
                  <input
                      type="password"
                      id="password"
                      name="password"
                      placeholder="비밀번호를 입력해주세요."
                      onkeyup="enterkey(this)"
                  />
              </div>
              <p class="error" id="login-error"></p>
          </div>
          <div class="find">
              <a href="{% url 'website:find_username' %}">아이디 찾기</a>|
              <a href="{% url 'website:password_reset' %}">비밀번호 찾기</a>
          </div>
          <button type="button" id="btn-login">로그인</button>
      </form>
      <div class="not_">
          <span
              >지금 가입하고 D'Nova의 혁신적인 서비스를
              경험해보세요!</span
          >
          <a href="{% url 'website:signup' %}">
              아직 회원이 아니신가요? <span>회원가입</span>
          </a>
      </div>
  </div>
</section>
{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'website/js/script_user_login.js' %}?v=20241220"></script>
{% endblock javascripts %}

buzzwave/website/templates/authentication/user_signup.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block title %}
  <title>D'Nova | 회원가입</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/register.css' %}" />
{% endblock stylesheets %}

<p class="success"></p>
<p class="error"></p>
{% block content %}
<section class="login_section">
  <div class="login_container container">
      <form id="signupForm">
          <h2>회원가입</h2>
          <div class="i-box_container">
              <div class="i-box">
                  <label for="membername">이름</label>
                  <input
                      type="text"
                      id="membername"
                      name="membername"
                      placeholder="이름을 입력해주세요."
                      required
                  />
                  <p class="error" id="message-membername"></p>
              </div>
              <div class="i-box">
                  <label for="email">이메일</label>
                  <input
                      type="email"
                      id="email"
                      name="email"
                      placeholder="이메일을 입력해주세요."
                      required
                      onchange="checkEmail()"
                  />
                  <p class="error" id="message-email"></p>
                  <p style="padding-left: 0.5rem;">가입완료 후 계정 활성화를 위한 인증 메일이 발송됩니다.</p>
              </div>
              <div class="i-box">
                  <label for="username">아이디</label>
                  <input
                      type="text"
                      id="username"
                      name="username"
                      placeholder="아이디를 입력해주세요."
                      required
                      onchange="checkUsername()"
                  />
                  <p class="error" id="message-username"></p>
              </div>
              <div class="i-box">
                  <label for="password">비밀번호</label>
                  <input
                      type="password"
                      id="password"
                      name="password"
                      placeholder="비밀번호를 입력해주세요."
                      required
                      onchange="checkPassword()"
                  />
                  <input
                      type="password"
                      id="re-password"
                      name="re-password"
                      placeholder="비밀번호를 다시 입력해주세요."
                      required
                      onchange="checkPassword()"
                  />
                  <p class="error" id="message-password"></p>
              </div>
              <div class="i-box">
                  <label for="phone">휴대폰번호</label>
                  <input
                      type="text"
                      id="phone"
                      name="phone"
                      placeholder="휴대폰번호를 입력해주세요."
                      required
                      maxlength="11" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
                  />
                  <p class="error" id="message-phone"></p>
              </div>
              <div class="i-box">
                  <label for="birth">생년월일</label>
                  <input
                      type="text"
                      id="birth"
                      name="birth"
                      placeholder="생년월일을 입력해주세요. (ex. yyyymmdd)"
                      required
                      maxlength="8" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" onchange="checkBirth()"
                  />
              </div>
              <div class="i-box">
                  <label for="company">회사</label>
                  <input
                      type="text"
                      id="company"
                      name="company"
                      placeholder="회사명을 입력해주세요."
                      required
                      maxlength="50"
                  />
              </div>
          </div>
          <p class="error" id="signup-error"></p>
          <button type="button" id="btn-submit">회원가입</button>
      </form>
      <div class="not_">
          <span>
              지금 로그인하고 D'Nova의 혁신적인 서비스를
              경험해보세요!
          </span>
          <a href="{% url 'website:login' %}">
              이미 회원이신가요? <span>로그인 하기</span>
          </a>
      </div>
  </div>
</section>
{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'website/js/script_user_signup.js' %}?v=20250103"></script>
{% endblock javascripts %}

buzzwave/website/templates/blog/blog.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
  <title>D'Nova | Blog</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}?v=20241220" />
{% endblock stylesheets %}


{% block content %}
<div class="blog">
  <div class="container">
      <div class="search_inner">
        <form method="get">
          <div class="search">
              <img
                  src="{% static 'images/icons/icon_search.svg' %}"
                  alt="검색"
              />
              <input
                  type="text"
                  name="search"
                  placeholder="검색어를 입력하세요"
                  value="{{search}}"
              />
          </div>
        </form>
      </div>
  </div>
  <div class="blog_container container">
      <aside class="blog_aside">
          <div class="s-box">
              <span>태그 목록</span>
          </div>
          <nav class="blog_nav">
              <ul>
                  {% if user.is_superuser %}
                    <li><a href="{% url 'website:blog_create' %}"><b>*** 글 작성하기 ***</b></a></li>
                  {% endif %}
                  <li {% if not tag %}class="active"{% endif %} ><a href="{% url 'website:blog'%}">전체보기  ({{blog_total_count}})</a></li>
                  {% for i in blog_tag_list %}
                  <li {% if i.name == tag %}class="active"{% endif %}><a href="{% url 'website:blog'%}?tag={{i.name}}">{{i.name}}  ({{i.tag_count}})</a></li>
                  {% endfor %}
              </ul>
          </nav>
      </aside>
      <article class="blog-list_container">
          {% if search %}
            <span style="font-size: 1.8rem;">총 <strong>{{search_count|intcomma}}개</strong>의 포스트를 찾았습니다.</span>
          {% endif %}
          <ul class="blog-list">
            {% for i in page_obj %}
              <li>
                  <a href="{% url 'website:blog_detail' i.id %}">
                    {% if i.imageUrl %}
                      <img src="{{i.imageUrl}}" alt="Blog-post Thumbnail"/>
                    {% else %}
                      <img
                          src="{% static 'images/dummy/rec.png' %}"
                          alt="더미이미지"
                      />
                    {% endif %}
                  </a>
                  <div class="blog-info">
                      <a href="{% url 'website:blog_detail' i.id %}">{{i.title}}</a>
                      <p>{{i.content|striptags|truncatechars:250|safe}}</p>
                  </div>
                  <div class="blog-detail">
                      <span class="date">{{ i.created_at|date:"Y년 m월 d일" }}</span>
                  </div>
                  {% if i.tags %}
                  <div class="tag_container">
                    <ul>
                      {% for tag in i.tags %}
                        <li>
                            <a href="{% url 'website:blog'%}?tag={{tag}}">{{tag}}</a>
                        </li>
                      {% endfor %}
                    </ul>
                </div>
                {% endif %}                  
              </li>
            {% endfor %}
          </ul>
          {% include 'pagination.html' %}
      </article>
  </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="{% static 'website/js/script_pagination.js' %}"></script>
{% endblock javascripts %}

buzzwave/website/templates/blog/blog_detail.html
{% extends "layouts/website_base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
  <title>D'Nova | {{blog.title}}</title>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/post.css' %}?v=20250103" />
{% endblock stylesheets %}


{% block content %}
<div class="blog">
  <div class="blog_container container">
      <article class="blog-list_container">
          <ul class="blog-list">
              <li>
                  <div class="t-box">
                      <h2>
                        {{blog.title}}
                      </h2>
                      <div class="blog-detail">
                          <span class="date">{{ blog.created_at|date:"Y년 m월 d일" }}</span>
                          {% if user.is_superuser %}
                            <a class="date" href="{% url 'website:blog_edit' blog.pk %}"> | <i class="fa-solid fa-pen-to-square"></i> 수정</a>
                            <a class="date" href="javascript:;" onclick="deletePost(this)"> | <i class="fa-solid fa-trash"></i> 삭제</a>
                          {% endif %}
                      </div>
                      {% if blog.blog_tag.all %}
                      <div class="tag_container">
                          <ul>
                            {% for i in blog.blog_tag.all %}
                              <li>
                                <a href="{% url 'website:blog'%}?tag={{i.tag.name}}" rel="tag">{{i.tag.name}}</a>
                              </li>
                            {% endfor %}
                          </ul>
                      </div>
                      {% endif %}
                  </div>
                  <a href="#">
                    {% if blog.image %}
                      <img src="{{blog.image.url}}" alt="Blog-post Thumbnail"/>
                    {% else %}
                      <img src="{% static 'images/dummy/rec.png' %}"alt="더미이미지"/>
                    {% endif %}
                  </a>
                  <div class="blog-info">
                      <p>
                        {{blog.content|safe}}
                      </p>
                  </div>
              </li>
          </ul>
      </article>
  </div>
</div>
{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'website/js/script_blog_detail.js' %}?v=20241220"></script>
{% endblock javascripts %}